name: Robot Framework Web-UI Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install library
      run: |
        sudo apt-get install -y xvfb wget ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcups2 libdbus-1-3 libgbm1 libgtk-3-0 libnspr4 libnss3 libxcomposite1 libxkbcommon0 libxrandr2 xdg-utils ntpdate openssl
    - name: Install library two
      run: |
        python3 -m pip install --disable-pip-version-check robotframework && pip install robotframework-seleniumlibrary && pip install xvfbwrapper && pip install robotframework-xvfb && pip install selenium
    - name: Install browser
      run: |
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
        && sudo dpkg -i google-chrome*.deb \
        && rm google-chrome*.deb \
        && chmod +x /driver/chromedriver
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test with robot
      run: |
        robot -d ./reports tests
    - name: Reporting
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Reports
        path: reports
