name: Robot Framework Web-UI Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install browser
      run: |
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
        && sudo dpkg -i google-chrome*.deb \
        && rm google-chrome*.deb \
        && wget -q https://chromedriver.storage.googleapis.com/103.0.5060.53/chromedriver_linux64.zip \
        && unzip chromedriver_linux64.zip \
        && rm chromedriver_linux64.zip \
        && sudo chmod 777 /usr/bin/google-chrome \
        && mv chromedriver /usr/bin/google-chrome \
        && chmod +x /usr/bin/google-chrome/chromedriver
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test with robot
      run: |
        robot -d ./reports tests
    - name: Reporting
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Reports
        path: reports
