name: Labu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 07 * * 1-5'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install browser
      run: |
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
        && sudo dpkg -i google-chrome*.deb \
        && rm google-chrome*.deb \
        && wget -q https://chromedriver.storage.googleapis.com/103.0.5060.24/chromedriver_linux64.zip \
        && unzip chromedriver_linux64.zip \
        && rm chromedriver_linux64.zip \
        && mv chromedriver /usr/local/bin \
        && chmod +x /usr/local/bin/chromedriver
    - name: Test with robot
      run: |
        robot -d ./reports tests/coba.robot
    - name: Reporting
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Reports
        path: reports
